### ISSUE TITLE
Wrong drexel-thesis.cls file under Template/v0.15 folder

### ISSUE THREAD

**Issue by DarkAlexWang** [DrexelPhysics/DissertationDocs#53]
To whom may concern,
First, I want to thank you for this great dissertation template, it saved me a lot of time!

I noticed that the drexel-thesis.cls file under Template/v0.15 folder is not a class file, it is a .dtx file instead.

**Comment by thoppe** [comment]
@DarkAlexWang Feel free to submit a PR (pull request) and if it look good we'll merge it in for the next user.
